/*
 * This source file was generated by the Gradle 'init' task
 */
package numer0n;

import numer0n.service.NumeronManager;
import numer0n.service.impl.NumeronManagerImpl;

public class App {

    public static void main(String[] args) {

     NumeronManager gameManager = new NumeronManagerImpl();
     gameManager.start();
        // ゲームを開始
    }
}
